### ISSUE TITLE
metaploit listener

### ISSUE THREAD

**Issue by sparta34** [mado-95/madwin#2]
what listener should using in metasploit with these payloads ?thanks

**Comment by mado-95** [comment]
It's a C++ socket so it uses netcat as a listener instead of Metasploit. Keep in mind the netcat port is randomized during payload creation, so you'll have to run the listener via `madwin.sh` or `server.sh`. At the moment Metasploit payloads aren't supported but they'll be integrated in the next update.

For reference, this is the command the listener runs:
`nc -lvp $default_port2`

**Comment by sparta34** [comment]
oh ok thanks for your time and good luck
